name: Deploy a GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Subir artefactos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4